# Generated by Django 4.1.3 on 2022-11-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(help_text='Track title', max_length=150, unique=True, verbose_name='title'),
        ),
    ]
